# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJIWu1igCMNTnaOzs7B5cDig9Mj1vgf8
"""

import streamlit as st
import joblib
import os

# -------------------------------------------------
# Step 1: Check that the saved model files exist
# -------------------------------------------------
# These two files were created earlier during training in Google Colab.
# We need them now because the Streamlit app will LOAD the trained model
# instead of training a new model from scratch.
required_files = [
    "svm_news_classifier.joblib",
    "target_names.joblib"
]

# This creates a list of any missing files.
missing_files = [f for f in required_files if not os.path.exists(f)]

# If one or both files are missing, show an error in the app and stop.
if missing_files:
    st.error("Missing files: " + ", ".join(missing_files))
    st.stop()

# -------------------------------------------------
# Step 2: Load the trained model and target names
# -------------------------------------------------
# joblib.load() opens the saved files and brings them back into memory.
# model = the trained SVM classifier
# target_names = the list of category names
model = joblib.load("svm_news_classifier.joblib")
target_names = joblib.load("target_names.joblib")

# -------------------------------------------------
# Step 3: Set up the Streamlit page
# -------------------------------------------------
# This controls the title shown in the browser tab and the page layout.
st.set_page_config(page_title="20 Newsgroups SVM Classifier", layout="centered")

# Main title shown inside the app
st.title("20 Newsgroups SVM Text Classifier")

# Short explanation for the user
st.write("Enter text below and click Classify to predict its category.")

# -------------------------------------------------
# Step 4: Create the text input area
# -------------------------------------------------
# This creates a large text box where the user can type or paste text.
user_text = st.text_area(
    "Enter text to classify:",
    height=200,
    placeholder="Type a sentence or paragraph here..."
)

# -------------------------------------------------
# Step 5: Create the Classify button
# -------------------------------------------------
# When the button is clicked, the code inside this block runs.
if st.button("Classify"):

    # If the user did not type anything, show a warning.
    if not user_text.strip():
        st.warning("Please enter some text first.")

    else:
        # -------------------------------------------------
        # Step 6: Make a prediction
        # -------------------------------------------------
        # model.predict([user_text]) returns a numeric category label.
        # We use [user_text] with brackets because the model expects
        # a list of documents, even if there is only one.
        prediction_index = model.predict([user_text])[0]

        # Convert the numeric prediction into the actual category name
        predicted_category = target_names[prediction_index]

        # -------------------------------------------------
        # Step 7: Display the result
        # -------------------------------------------------
        st.success(f"Predicted Category: {predicted_category}")